// import Components from 'components';

const routerConfig = {
  noAuthRoutes: ['error404', 'confirmemail', 'resetpassword', 'termsandconditions'],
  queryParams: ['token', 'uid', 'email', 'state', 'tab', 'name', 'modal'],
  persistantQueryParams: ['features'],
  groups: {
    organization: {
      id: 'organization',
      name: '',
    },
    admin: {
      id: 'admin',
      name: '',
    },
    support: {
      id: 'support',
      name: 'support',
    },
  },
  categories: {
    dashboard: {
      id: 'dashboard',
      name: 'Dashboard',
      group: 'organization',
      icon: 'mdi mdi-gauge',
    },
    invoices: {
      id: 'invoices',
      name: 'Invoices',
      group: 'organization',
      icon: 'mdi mdi-receipt',
    },
    payments: {
      id: 'payments',
      name: 'Payments',
      group: 'organization',
      icon: 'mdi mdi-file-multiple',
    },
    expenses: {
      id: 'expenses',
      name: 'Expenses',
      group: 'organization',
      icon: 'mdi mdi-receipt',
    },
    reports: {
      id: 'reports',
      name: 'Reports',
      group: 'organization',
      icon: 'mdi mdi-clipboard-pulse',
    },
    settings: {
      id: 'settings',
      name: 'Settings',
      group: 'organization',
      icon: 'mdi mdi-cog',
    },
    admin: {
      id: 'admin',
      name: 'Admin',
      group: 'admin',
      icon: 'mdi mdi-account-key',
    },
    support: {
      id: 'support',
      name: 'Support',
      group: 'support',
      icon: 'mdi mdi-headset',
      onlyShowWithPrivileges: ['canAdministrateGlobalVendors'],
    },
    vendors: {
      id: 'vendors',
      name: 'Vendors',
      group: 'organization',
      icon: 'mdi mdi-store',
      onlyShowWithPrivileges: ['canAudit', 'canManageAccountsAndOrganizations'],
    },
  },
  routes: [{
    name: 'dashboard',
    displayName: 'Dashboard',
    path: '/',
    icon: false,
    category: 'dashboard',
    location: 'Components.routes.dashboard',
    loaded: ['account.featureFlags.status.fetched'],
    config: {
      availableFunds: true,
      spendSummary: false,
      pendingPayments: true,
      cardsIntegrationStatus: false,
      erpIntegrationStatus: true,
      dailySpendGraph: true,
      cardsActivity: false,
      spendByVendorPieChart: true,
      paymentMethodsStatus: true,
    },
  }, {
    name: 'invoices',
    displayName: 'Invoices',
    path: 'invoices/',
    icon: false,
    category: 'invoices',
    location: 'Components.routes.invoices',
    featureFlag: 'invoices',
    tabs: [{
      name: 'invoices',
      label: 'Invoices',
      component: 'Components.tables.invoices',
      icon: 'mdi-receipt',
    }, {
      name: 'uploadInvoice',
      label: 'Upload Invoice',
      component: 'Components.uploaders.invoices',
      icon: 'mdi-cloud-upload',
    }],
  }, {
    name: 'jobs',
    displayName: 'Jobs',
    path: 'jobs/',
    icon: false,
    category: 'jobs',
    onlyShowWithSpecificPolicies: ['jobs_*_*_update'],
    location: 'Components.routes.jobs',
  }, {
    name: 'create',
    displayName: 'Create',
    path: 'create/',
    icon: false,
    category: 'payments',
    onlyShowWithPrivileges: ['canManagePayments', 'isBuyer'],
    location: 'Components.routes.create',
    loaded: ['account.featureFlags.status.fetched'],
    tabs: [{
      name: 'payments',
      label: 'Payments',
      component: 'Components.uploaders.payment',
      icon: 'mdi-pencil-plus-outline',
      policies: ['payments_idOrganization_idAccount_create', 'achTransfers_idOrganization_idAccount_create'],
      featureFlag: 'paymentCreation',
    }, {
      name: 'paymentCards',
      label: 'Purchase Cards',
      component: 'Components.uploaders.paymentcards',
      icon: 'mdi-credit-card-plus-outline',
      policies: ['payments_idOrganization_idAccount_create', 'achTransfers_idOrganization_idAccount_create'],
      featureFlag: 'paymentCards',
    }, {
      name: 'plasticCards',
      label: 'Plastic Cards',
      component: 'Components.creators.plastic',
      icon: 'mdi-playlist-edit',
      policies: ['cards_idOrganization_idAccount_create'],
      featureFlag: 'plastic',
    }],
  }, {
    name: 'history',
    displayName: 'History',
    path: 'history/',
    icon: false,
    category: 'payments',
    onlyShowWithPrivileges: ['canAudit'],
    location: 'Components.routes.history',
    loaded: ['account.featureFlags.status.fetched'],
    tabs: [{
      name: 'paymentHistory',
      label: 'Payment History',
      component: 'Components.containers.paymenthistory',
      icon: 'mdi-cash-multiple',
      featureFlag: 'paymentCreation',
    }, {
      name: 'paymentCards',
      label: 'Purchase Card History',
      component: 'Components.tables.paymentcards',
      icon: 'mdi-credit-card-outline',
      featureFlag: 'paymentCards',
    }, {
      name: 'transactionHistory',
      label: 'Transaction History',
      component: 'Components.tables.virtualcardtransactionhistory',
      icon: 'mdi-history',
    }, {
      name: 'plasticCards',
      label: 'Plastic Card History',
      component: 'Components.tables.plasticcards',
      icon: 'mdi-credit-card-multiple-outline',
      featureFlag: 'plastic',
    }],
  }, {
    name: 'vendors',
    displayName: 'Vendors',
    path: 'vendors/',
    icon: false,
    category: 'payments',
    location: 'Components.routes.vendors',
    onlyShowWithSpecificPolicies: ['vendors_idOrganization_idAccount_read'],
    loaded: ['account.erpIntegration.status.fetched'],
    tabs: [{
      name: 'uploadVendors',
      label: 'Upload Vendors',
      component: 'Components.uploaders.accountvendor',
      icon: 'mdi-cloud-upload',
      featureFlag: 'vendorCreateUpload',
    }, {
      name: 'createAVendor',
      label: 'Create A Vendor',
      component: 'Components.creators.accountvendor',
      icon: 'mdi-pencil',
      featureFlag: 'vendorCreateSingle',
    }],
  }, {
    name: 'clients',
    displayName: 'Clients',
    path: 'clients/',
    icon: false,
    category: 'payments',
    onlyShowWithSpecificPolicies: ['clients_idOrganization_idAccount_read', 'clientVendorLinks_idOrganization_idAccount_read'],
    location: 'Components.routes.clients',
    loaded: ['account.clients.status.fetched', 'account.clientVendorLinks.status.fetched'],
    featureFlag: 'clients',
    tabs: [{
      name: 'clients',
      label: 'Clients',
      component: 'Components.containers.clients',
      icon: 'mdi-cloud-upload',
      featureFlag: 'clients',
      policies: ['clients_idOrganization_idAccount_read'],
    }, {
      name: 'clientVendorLinks',
      label: 'Client-Vendor Links',
      component: 'Components.containers.clientVendorLinks',
      icon: 'mdi-pencil',
      featureFlag: 'clients',
      policies: ['clientVendorLinks_idOrganization_idAccount_create'],
    }],
  }, {
    name: 'expenseReportApprovals',
    displayName: 'Approvals',
    path: 'expenses-report-approvals/',
    icon: false,
    category: 'expenses',
    onlyShowWithSpecificPolicies: ['expenseReportApprovals_idOrganization_idAccount_create'],
    location: 'Components.routes.expenseReportApprovals',
    loaded: ['account.expenseReports.status.fetched'],
    featureFlag: 'expenses',
    tabs: [{
      name: 'pendingReports',
      label: 'Pending Reports',
      component: 'Components.containers.pendingExpenseReports',
      icon: 'mdi-timer-sand-empty',
      featureFlag: 'expenses',
    }, {
      name: 'rejectedReports',
      label: 'Rejected Reports',
      component: 'Components.containers.rejectedExpenseReports',
      icon: 'mdi-delete-outline',
      featureFlag: 'expenses',
    }, {
      name: 'completedReports',
      label: 'Completed Reports',
      component: 'Components.containers.completedExpenseReports',
      icon: 'mdi-check-bold',
      featureFlag: 'expenses',
    }],
  }, {
    name: 'expenses',
    displayName: 'My Expenses',
    path: 'expenses/',
    icon: false,
    category: 'expenses',
    onlyShowWithSpecificPolicies: ['expenses_idOrganization_idAccount_read'],
    location: 'Components.routes.expenses',
    loaded: ['account.expenses.status.fetched'],
    featureFlag: 'expenses',
  }, {
    name: 'expenseReports',
    displayName: 'My Expense Reports',
    path: 'expense-reports/',
    icon: false,
    category: 'expenses',
    onlyShowWithSpecificPolicies: ['expenseReports_idOrganization_idAccount_read'],
    location: 'Components.routes.expenseReports',
    loaded: ['account.expenseReports.status.fetched'],
    featureFlag: 'expenses',
  }, {
    name: 'createreport',
    displayName: 'Create Reports',
    path: 'create-report/',
    icon: false,
    category: 'reports',
    onlyShowWithPrivileges: ['canAudit'],
    location: 'Components.routes.createreport',
  }, {
    name: 'scheduledreports',
    displayName: 'Scheduled Reports',
    path: 'scheduled-reports/',
    icon: false,
    category: 'reports',
    onlyShowWithPrivileges: ['canAudit'],
    location: 'Components.routes.scheduledreports',
  }, {
    name: 'completedreports',
    displayName: 'Completed Reports',
    path: 'completed-reports/',
    icon: false,
    category: 'reports',
    onlyShowWithSpecificPolicies: ['reports_idOrganization_idAccount_read', 'statements_idOrganization_idAccount_read'],
    location: 'Components.routes.completedreports',
    tabs: [{
      name: 'standard',
      label: 'Transaction Reports',
      component: 'Components.cards.completedreports',
      icon: 'mdi-file-document',
      policies: ['reports_idOrganization_idAccount_read'],
    }, {
      name: 'revenueShares',
      label: 'Revenue Share Reports',
      component: 'Components.cards.completedrevenueshares',
      icon: 'mdi-file-check',
      policies: ['statements_idOrganization_idAccount_read'],
    }],
  }, {
    name: 'profile',
    displayName: 'Profile',
    path: 'profile/',
    icon: false,
    category: 'settings',
    location: 'Components.routes.profile',
    hideAccountContext: true,
    tabs: [{
      name: 'profile',
      label: 'User Profile',
      component: 'Components.entities.userprofile',
      icon: 'mdi-account',
    }, {
      name: 'preferences',
      label: 'User Preferences',
      component: 'Components.usersettings',
      icon: 'mdi-cog',
    }],
  }, {
    name: 'account',
    displayName: 'Account',
    path: 'account/',
    icon: false,
    category: 'settings',
    onlyShowWithPrivileges: ['canAudit', 'canManageAccountsAndOrganizations'],
    location: 'Components.routes.account',
    tabs: [{
      name: 'account',
      label: 'Account Settings',
      component: 'Components.accountSettings',
      icon: 'mdi-account',
      config: {
        virtualCardLogo: true,
        fundingPreferences: true,
        erpIntegration: true,
      },
    }, {
      name: 'payment',
      label: 'Payment Settings',
      component: 'Components.paymentSettings',
      icon: 'mdi-cash-usd-outline',
      policies: ['globalVendors_*_read'],
      config: {
        transferSettings: true,
        fundingPreferences: true,
        cardsIntegration: true,
        checksIntegration: true,
        achIntegration: true,
        erpIntegration: true,
        paymentPipelinePreferences: true,
        paymentCustomFields: true,
        paymentCardCustomFields: true,
        accountVendorCredentials: true,
        customFileParser: true,
      },
    }, {
      name: 'developer',
      label: 'Developer Settings',
      component: 'Components.developerSettings',
      icon: 'mdi-cog',
      policies: ['apiKeys_idOrganization_idAccount_read'],
      featureFlag: 'apiKeys',
    }],
  }, {
    name: 'organization',
    displayName: 'Organization',
    path: 'organization/',
    icon: false,
    category: 'settings',
    onlyShowWithPrivileges: ['canAudit', 'canManageAccountsAndOrganizations'],
    location: 'Components.routes.organization',
    tabs: [{
      name: 'organization',
      label: 'Organization',
      component: 'Components.entities.organization',
      icon: 'mdi-account',
    }, {
      name: 'preferences',
      label: 'Organization Preferences',
      component: 'Components.organizationSettings',
      icon: 'mdi-cog',
    }],
  }, {
    name: 'organizations',
    displayName: 'Organizations',
    path: 'organizations/',
    icon: false,
    category: 'admin',
    onlyShowWithSpecificPolicies: ['organizations_idOrganization_read'],
    location: 'Components.routes.organizations',
  },
  {
    name: 'users',
    displayName: 'Users',
    path: 'users/',
    icon: false,
    category: 'admin',
    onlyShowWithPrivileges: ['canAudit', 'canManageUsers'],
    location: 'Components.routes.users',
  }, {
    name: 'accounts',
    displayName: 'Accounts',
    path: 'accounts/',
    icon: false,
    category: 'admin',
    onlyShowWithPrivileges: ['canAudit', 'canManageAccountsAndOrganizations'],
    location: 'Components.routes.accounts',
  },
  {
    name: 'csrdashboard',
    displayName: 'Dashboard',
    path: 'csrdashboard/',
    icon: false,
    category: 'support',
    location: 'Components.routes.csrdashboard',
    onlyShowWithSpecificPolicies: ['globalVendors_*_read'],
  },
  {
    name: 'resourceoverview',
    displayName: '',
    path: ':resource/:id',
    icon: false,
    category: '',
    location: 'Components.routes.resourceoverview',
  },
  {
    name: 'globalvendors',
    displayName: 'Global Database',
    path: 'globalvendors/',
    icon: false,
    category: 'support',
    defaultTitle: 'Global Vendors',
    location: 'Components.routes.globalvendors',
    onlyShowWithSpecificPolicies: ['globalVendors_*_read'],
    tabTitles: {
      fields: 'Global Vendor Fields',
      creds: 'Global Vendor Creds',
      globalVendors: 'Global Vendors',
      tags: 'Global Vendor Tags',
      groups: 'Global Vendor Groups',
      metrics: 'Global Database Metrics',
    },
  },
  {
    name: 'ftpPayments',
    displayName: 'FTP Payments',
    path: 'ftpPayments/',
    icon: false,
    category: 'support',
    defaultTitle: 'FTP Payments',
    location: 'Components.routes.ftpPayments',
    onlyShowWithSpecificPolicies: ['globalVendors_*_read'],
  },
  {
    name: 'exceptions',
    displayName: 'Exceptions',
    path: 'exceptions/',
    icon: false,
    category: 'support',
    location: 'Components.routes.exceptions',
    onlyShowWithSpecificPolicies: ['globalVendors_*_read'],
  },
  {
    name: 'revenueshares',
    displayName: 'Revenue Shares',
    path: 'revenue-shares/',
    icon: false,
    category: 'admin',
    onlyShowWithSpecificPolicies: ['revenueShares_*_*_read', 'revenueShares_*_*_create'],
    location: 'Components.routes.revenueshares',
  }, {
    name: 'integrations',
    displayName: 'Integrations',
    path: 'integrations/',
    icon: false,
    category: 'admin',
    onlyShowWithSpecificPolicies: ['erpIntegration_*_*_read', 'achIntegration_*_*_read', 'fundingIntegration_*_*_read', 'cardsIntegration_*_*_read', 'checksIntegration_*_*_read'],
    location: 'Components.routes.integrations',
  },
  {
    name: 'features',
    displayName: 'Features',
    path: 'features/',
    icon: false,
    category: 'admin',
    onlyShowWithSpecificPolicies: ['globalVendors_*_read'],
    location: 'Components.routes.features',
    loaded: ['account.featureFlags.status.fetched'],
  },
  {
    name: 'error404',
    displayName: '404',
    path: '404/',
    icon: false,
    category: 'errors',
    location: 'Components.routes.error404',
  },
  {
    name: 'confirmemail',
    displayName: 'confirmEmail',
    path: 'confirmEmail/',
    icon: false,
    category: 'errors',
    location: 'Components.routes.confirmemail',
  },
  {
    name: 'fun',
    displayName: 'fun',
    path: 'fun/',
    icon: false,
    category: 'errors',
    location: 'Components.routes.fun',
  },
  {
    name: 'funding',
    displayName: 'Funding',
    path: 'funding/',
    icon: false,
    defaultTitle: 'Funding',
    category: 'payments',
    location: 'Components.routes.funding',
    featureFlag: 'fundingTab',
  },
  {
    name: 'resetpassword',
    displayName: 'resetPassword',
    path: 'resetPassword/',
    icon: false,
    category: 'errors',
    location: 'Components.routes.resetpassword',
  },
  {
    name: 'termsandconditions',
    displayName: 'Terms And Conditions',
    path: 'terms-and-conditions/',
    icon: false,
    location: 'Components.routes.termsandconditions',
  },
  {
    name: 'approvals',
    displayName: 'Approvals',
    path: 'approvals/',
    icon: false,
    location: 'Components.routes.approvals',
  }],
  resourceNameToOverview: {
    csrpayment: { component: ['csrPaymentStatus', 'paymentstatus'], componentTitles: ['CSR View', 'User View'], storePath: 'account.paymentStatuses' },
  },
};

export default routerConfig;

// GENERATOR_TYPE='exporter';
