import { connect, Component, bindActionCreators, Fragment } from 'component';

// Third Party Imports ...
import numeral from 'numeral';

import Utils from 'utils';
import Store from 'store';
import Selectors from 'selectors';
import Components from 'components';

import './index.scss';

const mapStateToProps = (state, props) => {
  return ({
    paymentCardChangeRequestsStatus: state.account.paymentCardChangeRequests.status,
    canUpdate: Selectors.entity('cards_idOrganization_idAccount')(state).canUpdate,
    paymentCardChangeRequests: state.account.paymentCardChangeRequests.data.items,
    filteredAndSortedItems: Selectors.tableItems('Components.tables.paymentCardChangeRequests', props.tableKey, 'state.account.paymentCardChangeRequests.data.items')(state),
  });
};

const mapDispatchToProps = (dispatch, props) => {
  return ({
    cancelPaymentCardChangeRequest: (id) => {
      return dispatch(Store.account.updatePaymentCard([{ id }], 'cancelPaymentCardChangeRequest'));
    },
    openAreYouSureModal: (data) => { dispatch(Store.router.openModal('Components.modals.areyousure', data)); },
  });
};

class components_tables_paymentCardChangeRequests extends Component {
  state = {
    columns: [
      { label: 'Status', dataKey: '_status', sortable: true, cellRenderer: data => <Components.badges.paymentCardChangeRequestStatus status={data} /> },
      { label: 'Funding Amount', dataKey: 'fundingAmount', sortable: true, cellRenderer: FormatAmount },
      { label: 'Date Submitted', dataKey: 'submittedAt', sortable: true, cellRenderer: (date) => { return Utils.dates.dateToDay(date); } },
      { label: 'Type', dataKey: 'type', sortable: true, cellRenderer: FormatType },
      { label: 'Submitted By', dataKey: 'submittedBy', default: '-', sortable: true, cellRenderer: (submittedBy) => { if (submittedBy === '-') return submittedBy; return <Components.badges.createdby user={submittedBy} />; } },
    ],
  };

  componentDidMount() {}
  componentWillUnmount() {}

  _generateActionContent = (paymentCardCR) => {
    const { canUpdate } = this.props;
    if (!canUpdate || paymentCardCR.type === 'create' || paymentCardCR._status === 'cancelled' || paymentCardCR._status === 'processed') return [];

    const popoverContent = [];
    popoverContent.push({
        title: 'Cancel',
        onClick: () => {
          this.props.openAreYouSureModal({
            title: 'Cancel Purchase Card Change',
            content: 'You are about to cancel the requested purchase card change, this change may have been generated by a trigger.',
            noText: 'No',
            yesText: 'Yes',
            onYes: () => {
              return this.props.cancelPaymentCardChangeRequest(paymentCardCR._id);
            },
          });
        },
        disabled: false,
    });

    return popoverContent;
  }

  render() {
    const { paymentCardChangeRequestsStatus, paymentCardChangeRequests, filteredAndSortedItems } = this.props;
    if (!_try(() => paymentCardChangeRequestsStatus.fetched)) return null;

    return (
      <Components.tables.components.collapsibleTable
        tableName="Components.tables.paymentCardChangeRequests"
        tableKey={this.props.tableKey}
        initialTableStateOverride={this.props.initialTableStateOverride}
        defaultTableState={{
          sort: {
            sortKey: 'submittedAt',
            orderIn: 'desc',
          },
        }}
        data={{
          items: paymentCardChangeRequests,
          count: _try(() => Object.keys(paymentCardChangeRequests).length, 0),
        }}
        itemOrder={_try(() => filteredAndSortedItems, [])}
        columns={this.state.columns}
        typeForNoDataText="Purchase Card Changes"
        doNotExpand
        actions={_try(() => filteredAndSortedItems.length > 1)}
        actionsInFirstColumn
        generateActionContent={_try(() => filteredAndSortedItems.length > 1) && this._generateActionContent}
        nestedTable={this.props.nestedTable}
        paginate
        initialRowsPerPage={10}
        hideRowsPerPageSelector={this.props.nestedTable}
      />
    );
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(components_tables_paymentCardChangeRequests);

// Internal Helper Functions ... 
const FormatAmount = (amount) => {
  return (amount) ? numeral(amount).format('$0,0.00') : 'Non-funding Change';
};

const FormatType = (type) => {
  let formattedType = 'Create';
  if (type === 'update') {
    formattedType = 'Manual Update';
  } else if (type === 'trigger') {
    formattedType = 'Trigger';
  }

  return formattedType;
};


