// import Components from 'components';

const routerConfig = {
  noAuthRoutes: ['error404', 'confirmemail', 'resetpassword', 'termsandconditions', 'authorize', 'oauthlogout'],
  queryParams: ['code', 'state', 'tab'],
  persistantQueryParams: ['admin', 'features'],
  groups: {
    organization: {
      id: 'organization',
      name: '',
    },
    admin: {
      id: 'admin',
      name: '',
    },
    support: {
      id: 'support',
      name: 'support',
    },
  },
  categories: {
    dashboard: {
      id: 'dashboard',
      name: 'Dashboard',
      group: 'organization',
      icon: 'mdi mdi-gauge',
    },
    payments: {
      id: 'payments',
      name: 'Payments',
      group: 'organization',
      icon: 'mdi mdi-file-multiple',
      onlyShowWithPrivileges: ['canManagePayments'],
    },
    reports: {
      id: 'reports',
      name: 'Reports',
      group: 'organization',
      icon: 'mdi mdi-clipboard-pulse',
    },
    expenses: {
      id: 'expenses',
      name: 'Expenses',
      group: 'organization',
      icon: 'mdi mdi-receipt',
    },
    settings: {
      id: 'settings',
      name: 'Settings',
      group: 'organization',
      icon: 'mdi mdi-cog',
    },
    admin: {
      id: 'admin',
      name: 'Admin',
      group: 'admin',
      icon: 'mdi mdi-account-key',
    },
  },
  routes: [{
    name: 'dashboard',
    displayName: 'Summary',
    path: '/dashboard',
    icon: false,
    category: 'dashboard',
    location: 'Components.routes.wfsDashboard',
    onlyShowWithPrivileges: ['canAudit'],
    config: {
      availableFunds: false,
      spendSummary: true,
      pendingPayments: false,
      cardsIntegrationStatus: false,
      erpIntegrationStatus: false,
      dailySpendGraph: false,
      cardsActivity: true,
      spendByVendorPieChart: false,
    },
  }, {
    name: 'history',
    displayName: 'History',
    path: '/',
    icon: false,
    category: 'dashboard',
    onlyShowWithPrivileges: ['canAudit', 'canViewAssignedCardTransactions'],
    location: 'Components.routes.wfsHistory',
    tabs: [{
      name: 'transactionHistory',
      label: 'Transaction History',
      component: 'Components.tables.virtualcardtransactionhistory',
      onlyShowWithPrivileges: ['canAudit', 'canViewAssignedCardTransactions'],
      icon: 'mdi-history',
    }, {
      name: 'plasticCards',
      label: 'Plastic Cards',
      component: 'Components.tables.plasticcards',
      onlyShowWithPrivileges: ['canAudit', 'canViewAssignedCardTransactions'],
      icon: 'mdi-credit-card-multiple-outline',
    }],
  }, {
    name: 'create',
    displayName: 'Create',
    path: 'create/',
    icon: false,
    category: 'payments',
    onlyShowWithPrivileges: ['canManagePayments', 'isBuyer'],
    location: 'Components.routes.wfsCreate',
    tabs: [
      {
        name: 'plasticCard',
        label: 'Plastic Cards',
        component: 'Components.creators.plastic',
        icon: 'mdi-email-plus-outline',
        policies: ['cards_idOrganization_idAccount_create'],
        // config: {
        //   forCreate: true,
        // },
      },
    ],
  }, {
    name: 'account',
    displayName: 'Account',
    path: 'account/',
    icon: false,
    category: 'settings',
    onlyShowWithPrivileges: ['canAudit', 'canManageAccountsAndOrganizations'],
    location: 'Components.routes.account',
    tabs: [{
      name: 'account',
      label: 'Account Settings',
      component: 'Components.entities.account',
      icon: 'mdi-account',
      config: {
        virtualCardLogo: false,
      },
    }, {
      name: 'payment',
      label: 'Payment Settings',
      component: 'Components.paymentSettings',
      icon: 'mdi-cash-usd-outline',
      config: {
        transferSettings: false,
        fundingPreferences: false,
        cardsIntegration: true,
        checksIntegration: false,
        achIntegration: false,
        erpIntegration: false,
        paymentPipelinePreferences: false,
        paymentCustomFields: false,
        paymentCardCustomFields: false,
        accountVendorCredentials: false,
        customFileParser: false,
      },
      options: {
        cardsIntegration: {
          onlyActivePlasticCards: true,
        },
      },
    }],
  }, {
    name: 'organization',
    displayName: 'Organization',
    path: 'organization/',
    icon: false,
    category: 'settings',
    onlyShowWithPrivileges: ['canAudit', 'canManageAccountsAndOrganizations'],
    location: 'Components.routes.organization',
    tabs: [{
      name: 'organization',
      label: 'Organization',
      component: 'Components.entities.organization',
      icon: 'mdi-account',
    }],
  }, {
    name: 'expenseReportApprovals',
    displayName: 'Approvals',
    path: 'expenses-report-approvals/',
    icon: false,
    category: 'expenses',
    onlyShowWithSpecificPolicies: ['expenseReportApprovals_idOrganization_idAccount_create'],
    location: 'Components.routes.expenseReportApprovals',
    loaded: ['account.expenseReports.status.fetched'],
    featureFlag: 'expenses',
    tabs: [{
      name: 'pendingReports',
      label: 'Pending Reports',
      component: 'Components.containers.pendingExpenseReports',
      icon: 'mdi-timer-sand-empty',
      featureFlag: 'expenses',
    }, {
      name: 'rejectedReports',
      label: 'Rejected Reports',
      component: 'Components.containers.rejectedExpenseReports',
      icon: 'mdi-delete-outline',
      featureFlag: 'expenses',
    }, {
      name: 'completedReports',
      label: 'Completed Reports',
      component: 'Components.containers.completedExpenseReports',
      icon: 'mdi-check-bold',
      featureFlag: 'expenses',
    }],
  }, {
    name: 'expenses',
    displayName: 'My Expenses',
    path: 'expenses/',
    icon: false,
    category: 'expenses',
    onlyShowWithSpecificPolicies: ['expenses_idOrganization_idAccount_read'],
    location: 'Components.routes.expenses',
    loaded: ['account.expenses.status.fetched'],
    featureFlag: 'expenses',
  }, {
    name: 'expenseReports',
    displayName: 'My Expense Reports',
    path: 'expense-reports/',
    icon: false,
    category: 'expenses',
    onlyShowWithSpecificPolicies: ['expenseReports_idOrganization_idAccount_read'],
    location: 'Components.routes.expenseReports',
    loaded: ['account.expenseReports.status.fetched'],
    featureFlag: 'expenses',
  }, {
    name: 'createreport',
    displayName: 'Create Reports',
    path: 'create-report/',
    icon: false,
    category: 'reports',
    onlyShowWithPrivileges: ['canAudit', 'canViewAssignedCardTransactions'],
    location: 'Components.routes.createreport',
  }, {
    name: 'scheduledreports',
    displayName: 'Scheduled Reports',
    path: 'scheduled-reports/',
    icon: false,
    category: 'reports',
    onlyShowWithPrivileges: ['canAudit', 'canViewAssignedCardTransactions'],
    location: 'Components.routes.scheduledreports',
  }, {
    name: 'completedreports',
    displayName: 'Completed Reports',
    path: 'completed-reports/',
    icon: false,
    category: 'reports',
    onlyShowWithSpecificPolicies: ['reports_idOrganization_idAccount_read', 'statements_idOrganization_idAccount_read'],
    location: 'Components.routes.completedreports',
    tabs: [{
      name: 'standard',
      label: 'Transaction Reports',
      component: 'Components.cards.completedreports',
      icon: 'mdi-file-document',
      policies: ['reports_idOrganization_idAccount_read'],
    }, {
      name: 'revenueShares',
      label: 'Revenue Share Reports',
      component: 'Components.cards.completedrevenueshares',
      icon: 'mdi-file-check',
      policies: ['statements_idOrganization_idAccount_read'],
    }],
  }, {
    name: 'users',
    displayName: 'Users',
    path: 'users/',
    icon: false,
    category: 'admin',
    onlyShowWithPrivileges: ['canAudit', 'canManageUsers'],
    defaultTitle: 'Users',
    location: 'Components.routes.users',
  }, {
    name: 'accounts',
    displayName: 'Accounts',
    path: 'accounts/',
    icon: false,
    category: 'admin',
    onlyShowWithPrivileges: ['canAudit', 'canManageAccountsAndOrganizations'],
    defaultTitle: 'Accounts',
    location: 'Components.routes.accounts',
  }, {
    name: 'integrations',
    displayName: 'Integrations',
    path: 'integrations/',
    icon: false,
    category: 'admin',
    onlyShowWithSpecificPolicies: ['erpIntegration_*_*_read', 'achIntegration_*_*_read', 'fundingIntegration_*_*_read', 'cardsIntegration_*_*_read', 'checksIntegration_*_*_read'],
    defaultTitle: 'Integrations',
    location: 'Components.routes.integrations',
  },
  {
    name: 'error404',
    displayName: '404',
    path: '404/',
    icon: false,
    category: 'errors',
    location: 'Components.routes.error404',
  },
  {
    name: 'oauthlogout',
    displayName: 'Logout',
    path: 'logout/',
    icon: false,
    location: 'Components.routes.oauthlogout',
  },
  {
    name: 'confirmemail',
    displayName: 'confirmEmail',
    path: 'confirmEmail/',
    icon: false,
    category: 'errors',
    location: 'Components.routes.confirmemail',
  },
  {
    name: 'resetpassword',
    displayName: 'resetPassword',
    path: 'resetPassword/',
    icon: false,
    category: 'errors',
    location: 'Components.routes.resetpassword',
  },
  {
    name: 'termsandconditions',
    displayName: 'Terms And Conditions',
    path: 'terms-and-conditions/',
    icon: false,
    location: 'Components.routes.termsandconditions',
  },
  {
    name: 'authorize',
    displayName: 'Authorize',
    path: 'authorize/',
    icon: false,
    location: 'Components.routes.authorize',
  }],
};

export default routerConfig;

// GENERATOR_TYPE='exporter';
