// Third Party Imports ...

function utils_getStatementFields() {
  const options = [
    'Account ID',
    'Account Number',
    'Advertiser Number',
    'Agency Name',
    'Amount',
    'Authorization Code',
    'Batch ID',
    'Candidate',
    'Card BIN Type',
    'Card Balance',
    'Card CTS',
    'Card Group',
    'Card Last 4',
    'Cardholder',
    'Cleared Amount',
    'Clearing Reference Number',
    'Company Number',
    'Conversion Fee',
    'Country Code',
    'Create Date',
    'Create ID',
    'Create Time',
    'Custom Field 1',
    'Custom Field 2',
    'Custom Field 3',
    'Custom Field 4',
    'Custom Field 5',
    'Custom Field 6',
    'Customer Billed Amount',
    'Customer Code',
    'Customer Fee',
    'Exact Match Flag',
    'Exchange Rate',
    'Expiration Date',
    'File Date',
    'Filename',
    'Flight Dates',
    'Global Vendor Ref',
    'Interchange Fee',
    'Interchange Rate Designator',
    'Interchange Rate',
    'Invoice Number',
    'Issue Amount',
    'Market',
    'Max Number of Uses',
    'Media Type',
    'Memo',
    'Memo Date',
    'Memo Time',
    'Merchant Category Code (MCC)',
    'Merchant City',
    'Merchant DBA',
    'Merchant ID',
    'Merchant State',
    'Merchant Zip/Postal Code',
    'Organization ID',
    'Payment ID',
    'Payment Method',
    'Process Date',
    'Process Time',
    'Record Type',
    'Tax Amount',
    'Transaction Category Code (TCC)',
    'Transaction Count',
    'Transaction Currency',
    'Transaction Date',
    'Transaction Time',
    'Transaction Type',
    'Vendor ID',
    'Vendor Name',
  ];

  const initialValues = [
    'Company Number',
    'Card Last 4',
    'Card CTS',
    'Card BIN Type',
    'Process Date',
    'Transaction Date',
    'Cleared Amount',
    'Customer Billed Amount',
    'Transaction Currency',
    'Clearing Reference Number',
    'Merchant ID',
    'Merchant DBA',
    'Merchant City',
    'Merchant State',
    'Merchant Zip/Postal Code',
    'Country Code',
  ];

  return {
    options,
    initialValues,
  };
}

export default utils_getStatementFields;

