const UPLOAD_TEMPLATE = /** @type {const} */([
  'Local_Vendor_Names',
  'Global_Vendor_Name',
  'Global_Group_Name',
  'Card',
  'Virtual_Card_Delivery_Method',
  'Virtual_Card_Emails',
  'Virtual_Card_Fax_Numbers',
  'Virtual_Card_Notes',
  'Virtual_Card_Notify_On_Creation',
  'Virtual_Card_Notify_On_Creation_Emails',
  'Virtual_Card_Notify_On_Completion',
  'Virtual_Card_Notify_On_Completion_Emails',
  'Virtual_Card_Max_Per_Card_Amount',
  'Virtual_Card_Payment_Schema',
  'Virtual_Card_Credential_Schema',
  'Virtual_Card_CC_Emails',
  'Virtual_Card_Use_Fax_Template',
  'Virtual_Card_Use_Email_Template',
  'Virtual_Card_Hide_CCBIN_Number',
  'ACH',
  'Account_Number',
  'Routing_Number',
  'Delivery_Speed',
  'Ach_Delivery_Method',
  'Ach_Notes',
  'Ach_First_Name',
  'Ach_Last_Name',
  'Ach_Notify_On_Creation',
  'Ach_Notify_On_Creation_Emails',
  'Ach_Email',
  'Ach_Payment_Schema',
  'Ach_Credential_Schema',
  'VCard_Fee_Value',
  'VCard_Fee_Type',
  'VCard_Require_Unique_Amounts',
  'VCard_Bin'
]);

export default UPLOAD_TEMPLATE;

